apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devathib
  name: devthib
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devthib  # Pas de metadata, juste des matchLabels
  template:  # Vous devez encapsuler les containers sous "template.spec"
    metadata:
      labels:
        app: devthib
    spec:
      containers:
      - image: replace  # Remplacera "replace" par l'image réelle dans votre pipeline
        name: devthib-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /tmp
          name: vol
      volumes:
      - name: vol
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devathib
  name: devthib-svc
spec:
  type: NodePort
  selector:
    app: devthib
  ports:
  - port: 8888
    targetPort: 80
    protocol: TCP