apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devthi
  name: devthib
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devthib
  template:
    metadata:
      labels:
        app: devthib
    spec:
      containers:
      - image: replace
        name: devthib-container
        ports:
        - containerPort: 80  
        volumeMounts:
        - mountPath: /tmp
          name: vol
      volumes:
      - name: vol
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devthib
  name: devthib-svc
spec:
  type: NodePort
  selector:
    app: devthib
  ports:
  - port: 9999  
    targetPort: 80
    protocol: TCP